"use strict";
exports.__esModule = true;
var Calculator_1 = require("./Calculator");
var result1 = Calculator_1.Calculator.calculate(5, 10, 'ADDITION');
console.log(result1);
var result2 = Calculator_1.Calculator.calculate(5, 10, 'SUBTRACTION');
console.log(result2);
var result3 = Calculator_1.Calculator.calculate(5, 10, 'MULTIPLICATION');
console.log(result3);
var result4 = Calculator_1.Calculator.calculate(5, 10, 'DIVISION');
console.log(result4);
